# -*- coding: utf-8 -*-
"""Copy of emotion detection chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1botcHx6a04rkqo89MWhwOrLYrsYqODKZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D
from tensorflow.keras.layers import Dense, Dropout

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

print("TensorFlow version:", tf.__version__)

!wget -O emotions.csv "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/auto-mpg.csv"

!pip install -q datasets

from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion")

train_df = dataset["train"].to_pandas()
val_df = dataset["validation"].to_pandas()
test_df = dataset["test"].to_pandas()

print("Training:", train_df.shape)
print("Validation:", val_df.shape)
print("Testing:", test_df.shape)

"""##The dataset provides approximately 16,000 training, 2,000 validation, and 2,000 test examples, with the same six emotion labels."""

train_df.head()

emotion_names = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

train_df["emotion"] = train_df["label"].map(emotion_names)

train_df.head()

plt.figure(figsize=(8,5))

sns.countplot(
    data=train_df,
    x="emotion",
    order=list(emotion_names.values())
)

plt.title("Emotion Distribution")
plt.xlabel("Emotion")
plt.ylabel("Number of Samples")
plt.xticks(rotation=30)
plt.show()

X_train = train_df["text"].values
y_train = train_df["label"].values

X_val = val_df["text"].values
y_val = val_df["label"].values

X_test = test_df["text"].values
y_test = test_df["label"].values

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Testing samples:", len(X_test))

"""##The CNN cannot directly understand sentences.

I convert words into numbers using a tokenizer.
"""

max_words = 20000
max_length = 100

tokenizer = Tokenizer(
    num_words=max_words,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_val)
X_test_seq = tokenizer.texts_to_sequences(X_test)

"""##Sentences have different lengths, so i make them the same length."""

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=max_length,
    padding="post",
    truncating="post"
)

X_val_pad = pad_sequences(
    X_val_seq,
    maxlen=max_length,
    padding="post",
    truncating="post"
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=max_length,
    padding="post",
    truncating="post"
)

print(X_train_pad.shape)
print(X_val_pad.shape)
print(X_test_pad.shape)

"""##Build CNN Model"""

vocab_size = min(max_words, len(tokenizer.word_index) + 1)

model = Sequential([

    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_length
    ),

    Conv1D(
        filters=128,
        kernel_size=5,
        activation="relu"
    ),

    GlobalMaxPooling1D(),

    Dense(128, activation="relu"),

    Dropout(0.5),

    Dense(6, activation="softmax")
])

model.summary()

"""##Because we have 6 classes, I'll use sparse categorical cross-entropy."""

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

"""Train CNN"""

history = model.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=7,
    batch_size=64
)

"""##Accuracy graph"""

plt.figure(figsize=(8,5))

plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")

plt.title("CNN Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")

plt.title("CNN Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

"""##Evaluate model"""

test_loss, test_accuracy = model.evaluate(
    X_test_pad,
    y_test
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

"""##predictions"""

y_pred_prob = model.predict(X_test_pad)

y_pred = np.argmax(
    y_pred_prob,
    axis=1
)

print(y_pred[:20])

print(
    classification_report(
        y_test,
        y_pred,
        target_names=list(emotion_names.values())
    )
)

"""##Matrix"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=emotion_names.values(),
    yticklabels=emotion_names.values()
)

plt.title("Emotion Detection Confusion Matrix")
plt.xlabel("Predicted Emotion")
plt.ylabel("Actual Emotion")

plt.show()

"""##Create Emotion Prediction Function"""

def predict_emotion(text):

    sequence = tokenizer.texts_to_sequences([text])

    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding="post",
        truncating="post"
    )

    prediction = model.predict(padded, verbose=0)

    emotion_id = np.argmax(prediction)

    emotion = emotion_names[emotion_id]

    confidence = prediction[0][emotion_id]

    return emotion, confidence

text = "I am feeling very happy today!"

emotion, confidence = predict_emotion(text)

print("Emotion:", emotion)
print("Confidence:", round(float(confidence) * 100, 2), "%")

text = "I am really scared about what will happen."

emotion, confidence = predict_emotion(text)

print("Emotion:", emotion)
print("Confidence:", round(float(confidence) * 100, 2), "%")

"""##chatbot"""

responses = {
    "sadness": [
        "I'm sorry you're feeling sad. I'm here to listen.",
        "It sounds like you're having a difficult time.",
        "I hope things get better for you soon."
    ],

    "joy": [
        "That's wonderful! ",
        "I'm happy to hear that!",
        "You sound really positive today!"
    ],

    "love": [
        "That sounds really special ",
        "It's wonderful to hear such positive feelings.",
        "Love can be a beautiful feeling."
    ],

    "anger": [
        "It sounds like something has really frustrated you.",
        "Take a moment to breathe and relax.",
        "I understand that you're feeling angry."
    ],

    "fear": [
        "It sounds like you're worried or scared.",
        "Take a deep breath. I'm here to listen.",
        "It's okay to talk about what is worrying you."
    ],

    "surprise": [
        "Wow! That sounds unexpected!",
        "That must have been quite a surprise!",
        "Interesting! Tell me more about it."
    ]
}

import random

def chatbot(message):

    emotion, confidence = predict_emotion(message)

    response = random.choice(
        responses[emotion]
    )

    print("Detected Emotion:", emotion)
    print("Confidence:", round(float(confidence) * 100, 2), "%")
    print("Bot:", response)

chatbot("I got a new job today and I am extremely happy!")

print(" Emotion Detection Chatbot")
print("Type 'exit' to stop.")

while True:

    user_message = input("\nYou: ")

    if user_message.lower() == "exit":
        print("Bot: Goodbye! ")
        break

    chatbot(user_message)

model.save("emotion_cnn_model.h5")

import pickle

with open("tokenizer.pkl", "wb") as file:
    pickle.dump(tokenizer, file)

from google.colab import files

files.download("emotion_cnn_model.h5")
files.download("tokenizer.pkl")

